# Generated by Django 4.1.3 on 2022-12-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Room',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='group',
            new_name='room',
        ),
    ]
